# Generated by Django 4.0.1 on 2022-02-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kurs Adini Giriniz', max_length=50, null=True, verbose_name='Kurs Adi')),
                ('description', models.TextField(max_length=100, null=True, verbose_name='Kurs Aciklamasi')),
                ('image', models.ImageField(default='courses/', upload_to='courses/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
